### Dataset:
You can download this dataset from here:
https://www.kaggle.com/datasets/ensaran/mercedesbenz

### CSV

In [100]:
# numpy: numerical computing library for arrays and math operations
import pandas as pd

# numpy: numerical computing library for arrays and math operations
import numpy as np

# requests: library to make HTTP requests and fetch data from URLs
import requests

In [101]:
# StringIO: treats a string as a file object (for text data like CSV)
# BytesIO: treats bytes as a file object (for binary data like Excel)
from io import StringIO, BytesIO

In [102]:
data = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3')

In [103]:
# type(data): returns the data type/class of an object
type(data)

str

In [104]:
# StringIO(): creates an in-memory file-like object from a string
# used to convert string data into readable format for pandas
StringIO()

In [105]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [106]:
## Read from specific columns
df=pd.read_csv(StringIO(data), usecols=lambda x: x.upper() in['COL1','COL3'])

In [107]:
df

  col1  col3
0    x     1
1    a     2
2    c     3

In [108]:
# df.to_csv(): exports DataFrame to a CSV file
df.to_csv('Test(pt6).csv')

In [109]:
## Specifying columns datatypes
data = ('a,b,c,d\n'
        '1,2,3,4\n'
        '5,6,7,8\n'
        '9,10,11,12')

In [110]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12

In [111]:
df = pd.read_csv(StringIO(data),dtype=float)

In [112]:
df

     a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [113]:
df['a']

0    1.0
1    5.0
2    9.0
Name: a, dtype: float64

In [114]:
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':float,'a':'Int64'})

In [115]:
df

   a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [116]:
type(df['a'][1])

numpy.int64

In [117]:
## Check the datatype
df.dtypes

a      Int64
b      int64
c    float64
d      int64
dtype: object

In [118]:
## Index xolumns and training delimiters

In [119]:
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,')

In [120]:
pd.read_csv(StringIO(data))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [121]:
pd.read_csv(StringIO(data),index_col=False)

   a       b    c
0  4   apple  bat
1  8  orange  cow

In [122]:
## Combining usecols and index_col
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,')

In [123]:
pd.read_csv(StringIO(data), usecols=['b', 'c'],index_col=False)

        b    c
0   apple  bat
1  orange  cow

In [124]:
## Quoting and Escape Characters. Very useful in NlP
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [125]:
pd.read_csv(StringIO(data), escapechar='\\')

                               a  b
0  hello, "Bob", nice to see you  5

In [126]:
## URL to CSV

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
}

url = ('https://download.bls.gov/pub/time.series/cu/cu.item')
response = requests.get(url, headers=headers)
df = pd.read_csv(StringIO(response.text), sep='\t')
print(df.head())

  item_code                                          item_name  display_level  \
0       AA0                               All items - old base              0
1      AA0R  Purchasing power of the consumer dollar - old ...              0
2       SA0                                          All items              0
3      SA0E                                             Energy              1
4     SA0L1                                All items less food              1

  selectable  sort_sequence
0          T              2
1          T            400
2          T              1
3          T            375
4          T            359